service: durinn

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-west-2
  stackTags:
    Owner: Erwin
  deploymentBucket:
    name: edebusschere-durinn-lambda-test
    tags:
      Owner: Erwin
  apiName: durinn
  endpointType: regional

package:
  artifact: build/libs/durinn-1.0-SNAPSHOT-all.jar

functions:
  ping:
    handler: PingHandler::handle
    description: Basic healthcheck endpoint. Returns pong
    events:
      - http:
          path: /ping
          method: GET
  authorize:
    handler: AuthorizationHandler::handle
    events:
      - http:
          path: /authorize
          method: POST
